/**
 * מאגר המיקומים של חבילת "ישראל קלאסי".
 *
 * מאורגן לפי קטגוריה (ישוב / אתר) ובתוכה לפי דרגת קושי (קל / בינוני /
 * מקצוענים) — בדיוק כפי שהם נבחרים במשחק. דרגת הקושי קובעת אך ורק
 * מאיזה מאגר נבחר הפריט; היא אינה משפיעה על הניקוד.
 *
 * להוספת מיקום: הוסיפו רשומה לקבוצה המתאימה, עם מזהה יציב וייחודי
 * (kebab-case), שם תצוגה בעברית, וקואורדינטות מדויקות (WGS84). שדה
 * fact הוא רשות. מיד לאחר הוספה כדאי להריץ `npm test` — קיימת בדיקת
 * רגרסיה האורים שכל מיקום נופל בתוך גבולות היבשה המפושטת של המפה
 * ולא בים.
 */

import type { GameLocation } from './index.js';

/** ישובים — דרגת קושי קלה: הערים הגדולות והמוכרות ביותר בישראל. */
const SETTLEMENTS_EASY: readonly GameLocation[] = [
  {
    id: 'tel-aviv',
    name: 'תל אביב',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.0853, lng: 34.7818 },
    fact: 'נוסדה ב-1909 כשכונה צפונית ליפו, והיום מרכז כלכלי על חוף הים התיכון.',
  },
  {
    id: 'jerusalem',
    name: 'ירושלים',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 31.7683, lng: 35.2137 },
    fact: 'העיר הגדולה בישראל בשטח ובאוכלוסייה, ויושבת על קו פרשת המים ההררי.',
  },
  {
    id: 'haifa',
    name: 'חיפה',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.794, lng: 34.9896 },
    fact: 'נבנתה על מדרונות הכרמל, ובה נמל הים הגדול בישראל.',
  },
  {
    id: 'beer-sheva',
    name: 'באר שבע',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 31.253, lng: 34.7915 },
    fact: 'בירת הנגב, בצומת הדרכים המרכזי של דרום הארץ.',
  },
  {
    id: 'eilat',
    name: 'אילת',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 29.5577, lng: 34.9519 },
    fact: 'העיר הדרומית ביותר בישראל, על חופו של ים סוף.',
  },
  {
    id: 'ashdod',
    name: 'אשדוד',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 31.8014, lng: 34.6553 },
    fact: 'עיר נמל על חוף הים התיכון, כ-30 ק"מ דרומית לתל אביב.',
  },
  {
    id: 'netanya',
    name: 'נתניה',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.3215, lng: 34.8532 },
    fact: 'שוכנת במרכז מישור החוף, על מצוק הכורכר שמעל הים.',
  },
  {
    id: 'rishon-lezion',
    name: 'ראשון לציון',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 31.973, lng: 34.7925 },
  },
  {
    id: 'petah-tikva',
    name: 'פתח תקווה',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.0917, lng: 34.8872 },
  },
  {
    id: 'holon',
    name: 'חולון',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.0158, lng: 34.7874 },
  },
  {
    id: 'bat-yam',
    name: 'בת ים',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.0171, lng: 34.7522 },
  },
  {
    id: 'ramat-gan',
    name: 'רמת גן',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.0684, lng: 34.8248 },
  },
  {
    id: 'ashkelon',
    name: 'אשקלון',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 31.6693, lng: 34.5715 },
  },
  {
    id: 'rehovot',
    name: 'רחובות',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 31.8928, lng: 34.8113 },
  },
  {
    id: 'herzliya',
    name: 'הרצליה',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.1624, lng: 34.8447 },
  },
  {
    id: 'kfar-saba',
    name: 'כפר סבא',
    category: 'settlement',
    difficulty: 'easy',
    position: { lat: 32.175, lng: 34.907 },
  },
];

/** ישובים — דרגת קושי בינונית: ערים ועיירות מוכרות בפרסום בינוני. */
const SETTLEMENTS_MEDIUM: readonly GameLocation[] = [
  {
    id: 'tiberias',
    name: 'טבריה',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 32.7922, lng: 35.5312 },
    fact: 'יושבת על חופה המערבי של הכנרת, כ-200 מטר מתחת לפני הים.',
  },
  {
    id: 'dimona',
    name: 'דימונה',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.0703, lng: 35.0333 },
    fact: 'עיר פיתוח בנגב המזרחי, בדרך לים המלח.',
  },
  {
    id: 'nahariya',
    name: 'נהריה',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 33.006, lng: 35.098 },
  },
  {
    id: 'afula',
    name: 'עפולה',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 32.6078, lng: 35.2897 },
    fact: 'ליבו של עמק יזרעאל, ומכונה "בירת העמק".',
  },
  {
    id: 'safed',
    name: 'צפת',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 32.965, lng: 35.4951 },
    fact: 'העיר הגבוהה בישראל, בהרי הגליל העליון.',
  },
  {
    id: 'modiin',
    name: 'מודיעין',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.8928, lng: 35.0104 },
    fact: 'עיר מתוכננת בשפלה, בדיוק באמצע הדרך בין תל אביב לירושלים.',
  },
  {
    id: 'karmiel',
    name: 'כרמיאל',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 32.9186, lng: 35.2952 },
  },
  {
    id: 'kiryat-shmona',
    name: 'קריית שמונה',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 33.2074, lng: 35.5695 },
  },
  {
    id: 'beit-shean',
    name: 'בית שאן',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 32.4969, lng: 35.4989 },
  },
  {
    id: 'arad',
    name: 'ערד',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.2589, lng: 35.2128 },
  },
  {
    id: 'sderot',
    name: 'שדרות',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.5251, lng: 34.5958 },
  },
  {
    id: 'akko',
    name: 'עכו',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 32.9281, lng: 35.0818 },
  },
  {
    id: 'ramla',
    name: 'רמלה',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.9276, lng: 34.8625 },
  },
  {
    id: 'lod',
    name: 'לוד',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.9516, lng: 34.8956 },
  },
  {
    id: 'kiryat-gat',
    name: 'קריית גת',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.61, lng: 34.7642 },
  },
  {
    id: 'hebron',
    name: 'חברון',
    category: 'settlement',
    difficulty: 'medium',
    position: { lat: 31.52528, lng: 35.10833 },
    fact: 'העיר הגדולה בהרי חברון, ובה מערת המכפלה — מהאתרים המקודשים בעולם היהודי.',
  },
];

/** ישובים — דרגת קושי מקצוענים: יישובים קטנים, מושבים וקיבוצים. */
const SETTLEMENTS_PRO: readonly GameLocation[] = [
  {
    id: 'eli',
    name: 'עלי',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 32.07139, lng: 35.26528 },
    fact: 'יישוב קהילתי בהרי בנימין, על כביש 60 בין שילה לצומת תפוח.',
  },
  {
    id: 'sde-yitzhak',
    name: 'שדה יצחק',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 32.40389, lng: 34.99444 },
    fact: 'מושב בעמק חפר, מדרום-מזרח לחדרה.',
  },
  {
    id: 'netiv-haasara',
    name: 'נתיב העשרה',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 31.57083, lng: 34.53944 },
    fact: 'מושב חופי על גבול רצועת עזה, הידוע גם בקיר הציורים הצבעוני לאורך הגדר.',
  },
  {
    id: 'metula',
    name: 'מטולה',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 33.2706, lng: 35.5689 },
    fact: 'המושבה הצפונית ביותר בישראל, בקצה אצבע הגליל.',
  },
  {
    id: 'yotvata',
    name: 'יטבתה',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 29.8855, lng: 35.053 },
  },
  {
    id: 'neot-hakikar',
    name: 'נאות הכיכר',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 30.9449, lng: 35.3729 },
  },
  {
    id: 'paran',
    name: 'פארן',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 30.3634, lng: 35.1556 },
  },
  {
    id: 'kfar-vardim',
    name: 'כפר ורדים',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 32.996, lng: 35.2694 },
  },
  {
    id: 'amirim',
    name: 'אמירים',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 32.9372, lng: 35.4516 },
  },
  {
    id: 'yodfat',
    name: 'יודפת',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 32.8369, lng: 35.2715 },
  },
  {
    id: 'gesher-haziv',
    name: 'גשר הזיו',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 33.0391, lng: 35.1118 },
  },
  {
    id: 'urim',
    name: 'אורים',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 31.3042, lng: 34.5226 },
  },
  {
    id: 'kfar-blum',
    name: 'כפר בלום',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 33.1725, lng: 35.6098 },
  },
  {
    id: 'sde-eliyahu',
    name: 'שדה אליהו',
    category: 'settlement',
    difficulty: 'pro',
    position: { lat: 32.4404, lng: 35.5138 },
  },
];

/** אתרים — דרגת קושי קלה: הכי מוכרים בישראל, מוכרים לכולם. */
const LANDMARKS_EASY: readonly GameLocation[] = [
  {
    id: 'masada',
    name: 'מצדה',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 31.3156, lng: 35.3536 },
    fact: 'מבצר הרודיאני על צוק במדבר יהודה, מעל חופו המערבי של ים המלח.',
  },
  {
    id: 'dead-sea',
    name: 'ים המלח',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 31.2, lng: 35.3706 },
    fact: 'הנקודה היבשתית הנמוכה בעולם, ומימיו המליחים במיוחד מאפשרים לצוף בהם בקלות.',
  },
  {
    id: 'western-wall',
    name: 'הכותל המערבי',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 31.7767, lng: 35.2345 },
    fact: 'שריד לחומת התמך של הר הבית, מהאתרים המקודשים ביותר בעולם היהודי.',
  },
  {
    id: 'sea-of-galilee',
    name: 'הכנרת',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 32.83, lng: 35.59 },
    fact: 'אגם המים המתוקים הגדול בישראל, ומקור מים היסטורי מרכזי למדינה.',
  },
  {
    id: 'ben-gurion-airport',
    name: 'נמל התעופה בן-גוריון',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 32.0055, lng: 34.8854 },
    fact: 'שדה התעופה הבינלאומי הראשי של ישראל, סמוך ללוד.',
  },
  {
    id: 'mount-hermon',
    name: 'החרמון',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 33.305, lng: 35.785 },
    fact: 'הנקודה הגבוהה בשליטת ישראל, בקצה הצפוני של הארץ.',
  },
  {
    id: 'rosh-hanikra',
    name: 'ראש הנקרה',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 33.0862, lng: 35.1137 },
    fact: 'מערות קרסט לבנות על גבול לבנון, שנחצבו בפעולת גלי הים התיכון.',
  },
  {
    id: 'bahai-gardens',
    name: 'גני הבהאים',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 32.814, lng: 34.9885 },
    fact: 'גנים מדורגים על מדרון הכרמל בחיפה, מרכז העולם הבהאי ואתר מורשת עולמית.',
  },
  {
    id: 'timna-park',
    name: 'פארק תמנע',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 29.7694, lng: 34.9545 },
    fact: 'עמק מדברי בערבה עם תצורות סלע צבעוניות ומכרות נחושת עתיקים.',
  },
  {
    id: 'nimrod-fortress',
    name: 'מבצר נמרוד',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 33.2528, lng: 35.7147 },
    fact: 'מבצר איובי-ממלוכי על רכס בשלוחות החרמון, מהמבצרים הגדולים בישראל.',
  },
  {
    id: 'basilica-annunciation',
    name: 'כנסיית הבשורה, נצרת',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 32.7028, lng: 35.2977 },
    fact: 'הכנסייה הקתולית הגדולה במזרח התיכון, במקום שעל פי המסורת בשרה מרים.',
  },
  {
    id: 'akko-old-city',
    name: 'העיר העתיקה עכו',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 32.9234, lng: 35.0688 },
    fact: 'עיר נמל מוקפת חומות מתקופת הצלבנים והעות\'מאנים, אתר מורשת עולמית.',
  },
  {
    id: 'carmel-caves',
    name: 'מערות הכרמל',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 32.665, lng: 34.958 },
    fact: 'מערות פרהיסטוריות בנחל המערות שבכרמל, אתר מורשת עולמית.',
  },
  {
    id: 'bet-guvrin',
    name: 'גן לאומי בית גוברין',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 31.611, lng: 34.8983 },
    fact: 'מכונה "ארץ אלף המערות" בזכות מערות החציבה הרבות שבתחומו.',
  },
  {
    id: 'tower-of-david',
    name: 'מגדל דוד',
    category: 'landmark',
    difficulty: 'easy',
    position: { lat: 31.7767, lng: 35.228 },
    fact: 'מצודה עתיקה ליד שער יפו בעיר העתיקה בירושלים.',
  },
];

/** אתרים — דרגת קושי בינונית: גנים לאומיים ושמורות מוכרים למדי. */
const LANDMARKS_MEDIUM: readonly GameLocation[] = [
  {
    id: 'caesarea',
    name: 'קיסריה',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.5005, lng: 34.8938 },
    fact: 'עיר נמל רומית עתיקה שהקים הורדוס, עם תיאטרון, נמל ואמת מים שרידים.',
  },
  {
    id: 'ein-gedi',
    name: 'שמורת עין גדי',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 31.4577, lng: 35.3905 },
    fact: 'נווה מדבר על חופו המערבי של ים המלח, עם מפלים ובעלי חיים כמו יעל נובי.',
  },
  {
    id: 'banias',
    name: 'הבניאס',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 33.2486, lng: 35.6944 },
    fact: 'שמורת טבע בשלוחות החרמון, עם המפל הגדול בישראל ומקורות נהר הירדן.',
  },
  {
    id: 'avdat',
    name: 'עבדת',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 30.7942, lng: 34.7733 },
    fact: 'עיר נבטית לאורך דרך הקטורת, אתר מורשת עולמית בהרי הנגב.',
  },
  {
    id: 'tel-dan',
    name: 'שמורת תל דן',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 33.2473, lng: 35.6533 },
    fact: 'שמורת טבע בצפון החולה, סביב מקורות נהר הדן ותל העיר המקראית דן.',
  },
  {
    id: 'herodium',
    name: 'הרודיון',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 31.6658, lng: 35.2414 },
    fact: 'ארמון-מבצר מלאכותי בצורת הר געש שהקים הורדוס, ובו נטמן.',
  },
  {
    id: 'atlit-fortress',
    name: 'מצודת עתלית',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.7013, lng: 34.9359 },
    fact: 'מבצר צלבני על חצי אי בחוף הכרמל, מהמבצרים המרשימים שנותרו מהתקופה.',
  },
  {
    id: 'beit-shearim',
    name: 'גן לאומי בית שערים',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.7033, lng: 35.1292 },
    fact: 'בית קברות יהודי עתיק חצוב במערות, אתר מורשת עולמית ברגלי הכרמל.',
  },
  {
    id: 'tel-megiddo',
    name: 'תל מגידו',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.5853, lng: 35.1844 },
    fact: 'תל ארכיאולוגי מרובד בעמק יזרעאל, המזוהה עם "הר מגידו" המקראי.',
  },
  {
    id: 'tzipori',
    name: 'גן לאומי ציפורי',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.7456, lng: 35.2786 },
    fact: 'עיר רומית-ביזנטית בגליל התחתון, מוכרת בעיקר בזכות פסיפסיה המרהיבים.',
  },
  {
    id: 'gamla',
    name: 'שמורת גמלא',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.9049, lng: 35.7443 },
    fact: 'שמורת טבע ברמת הגולן עם המפל הגבוה בישראל ותצפית נשרים.',
  },
  {
    id: 'horshat-tal',
    name: 'גן לאומי חורשת טל',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 33.2205, lng: 35.6293 },
    fact: 'חורשת אלונים עתיקה סביב בריכות מים בעמק החולה הצפוני.',
  },
  {
    id: 'yehudiya-reserve',
    name: 'שמורת יהודיה',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.9378, lng: 35.7041 },
    fact: 'שמורת הקניונים הגדולה ברמת הגולן, עם מפלים ובריכות טבילה.',
  },
  {
    id: 'achziv',
    name: 'גן לאומי אכזיב',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 33.0478, lng: 35.1022 },
    fact: 'חוף וגן לאומי בגליל המערבי, עם בריכות סלע ותל העיר הכנענית העתיקה.',
  },
  {
    id: 'gan-hashlosha',
    name: 'גן השלושה (סחנה)',
    category: 'landmark',
    difficulty: 'medium',
    position: { lat: 32.5064, lng: 35.4462 },
    fact: 'בריכות טבעיות מוזנות מעיינות חמימים, לרגלי הגלבוע בעמק המעיינות.',
  },
];

/** אתרים — דרגת קושי מקצוענים: שמורות ואתרי מורשת פחות מוכרים. */
const LANDMARKS_PRO: readonly GameLocation[] = [
  {
    id: 'shivta',
    name: 'גן לאומי שבטה',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 30.8824, lng: 34.5328 },
    fact: 'עיר נבטית-ביזנטית שלמה בלב הנגב, לאורך דרך הקטורת העתיקה.',
  },
  {
    id: 'mamshit',
    name: 'גן לאומי ממשית',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.0261, lng: 35.0639 },
    fact: 'העיר הנבטית הקטנה והשמורה ביותר, ליד דימונה.',
  },
  {
    id: 'avshalom-cave',
    name: 'מערת הנטיפים',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.7069, lng: 34.9686 },
    fact: 'מערת סטלגמיטים וסטלגטיטים בהרי יהודה, שהתגלתה במקרה ב-1968.',
  },
  {
    id: 'nahal-amud',
    name: 'שמורת נחל עמוד',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 32.8752, lng: 35.502 },
    fact: 'קניון בגליל התחתון בין צפת לכנרת, ממסלולי המים הפופולריים בארץ.',
  },
  {
    id: 'mar-saba',
    name: 'מנזר מר סבא',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.7061, lng: 35.3547 },
    fact: 'מנזר יווני-אורתודוקסי הבנוי על צוק במדבר יהודה, מעל נחל קדרון.',
  },
  {
    id: 'britannia-park',
    name: 'פארק בריטניה',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.7007, lng: 34.9317 },
    fact: 'שמורת יער בשפלת יהודה עם בורות מים ומערות חציבה עתיקות.',
  },
  {
    id: 'dor-habonim',
    name: 'שמורת חוף דור הבונים',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 32.64, lng: 34.93 },
    fact: 'שמורת חוף סלעית בחוף הכרמל, עם מפרצונים, מערות ים ומדוזות תשתית.',
  },
  {
    id: 'khirbet-midras',
    name: 'חורבת מדרס',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.652, lng: 34.928 },
    fact: 'תל יישוב עתיק בפארק עדולם, עם מערכת מערות חבויה מרשימה.',
  },
  {
    id: 'tel-beer-sheva',
    name: 'תל באר שבע',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.2437, lng: 34.8402 },
    fact: 'תל מקראי המזוהה עם באר שבע העתיקה, אתר מורשת עולמית.',
  },
  {
    id: 'tel-hazor',
    name: 'תל חצור',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 33.0173, lng: 35.5668 },
    fact: 'התל הגדול בישראל, בירת ממלכה כנענית ואתר מורשת עולמית בחולה.',
  },
  {
    id: 'tel-arad',
    name: 'תל ערד',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.2811, lng: 35.1261 },
    fact: 'תל מקראי במישור ערד, ובו שרידי מקדש ישראלי נדיר.',
  },
  {
    id: 'ein-tzukim',
    name: 'שמורת עינות צוקים',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 31.63, lng: 35.435 },
    fact: 'שמורת מעיינות וביצות בחוף הצפוני של ים המלח, בית גידול נדיר.',
  },
  {
    id: 'korazim',
    name: 'גן לאומי כורזים',
    category: 'landmark',
    difficulty: 'pro',
    position: { lat: 32.916, lng: 35.564 },
    fact: 'שרידי בית כנסת עתיק מבזלת שחורה, מעל חופה הצפוני של הכנרת.',
  },
];

/** כל מיקומי חבילת "ישראל קלאסי", בסדר קבוע (ישוב/אתר × קל/בינוני/מקצוענים). */
export const ISRAEL_LOCATIONS: readonly GameLocation[] = [
  ...SETTLEMENTS_EASY,
  ...SETTLEMENTS_MEDIUM,
  ...SETTLEMENTS_PRO,
  ...LANDMARKS_EASY,
  ...LANDMARKS_MEDIUM,
  ...LANDMARKS_PRO,
];
